// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"xm-companies/config"
	"xm-companies/internal/xm-companies/db"
	"xm-companies/internal/xm-companies/security/otp/cotp"
	"xm-companies/internal/xm-companies/server"
	"xm-companies/internal/xm-companies/store/postgresql"
)

// Injectors from wire.go:

func BuildServerCompileTime() (*server.Server, error) {
	configConfig := config.NewConfigProvider()
	sqlDB, err := db.New(configConfig)
	if err != nil {
		return nil, err
	}
	usersRepository := postgresql.NewUsersRepositoryProvider(sqlDB)
	companiesRepository := postgresql.NewCompaniesRepositoryProvider(sqlDB)
	store := postgresql.NewStoreProvider(sqlDB, usersRepository, companiesRepository)
	service := cotp.NewServiceProvider(configConfig)
	serverServer := server.NewServerProvider(configConfig, store, service)
	return serverServer, nil
}
